### ISSUE TITLE
Add note about git version in README.md

### ISSUE THREAD

**Issue by f3rmion** [grimme-lab/multicharge#2]
**Problem**
Meson build error “ERROR: Git command failed” with git version 1.8.3.1

**Reason**
Git version 1.8.3.1 has no parameter called "-C"

**Solution**
Update to a newer git version (e.g., 2.21.0) solves this.

**Comment by awvwgk** [comment]
This seems to be a meson related issue rather than a restriction of this project. Checking repology on git it seems that most active distributions provide git with major version 2 (see https://repology.org/project/git/versions), assuming git with major version 2 seems like a reasonable default to me.

**Comment by awvwgk** [comment]
Changing the subdirectory with `-C` is available since version 1.8.5, so this was a close miss ;).

**Comment by f3rmion** [comment]
Totally agree, turns out the mentioned problematic git version seems to be still the default on our cluster. Cheers.
